import type { Plan, User, Notification } from "./types"

export const currentUser: User = {
  id: "user-1",
  name: "Carlos García",
  username: "carlosg",
  email: "carlos@email.com",
  phone: "+34 612 345 678",
  avatar: "/young-spanish-man-smiling.jpg",
  description: "Amante del deporte y las aventuras al aire libre. Siempre buscando nuevos planes!",
  interests: ["Deportes", "Senderismo", "Música", "Viajes"],
  location: {
    lat: 40.4168,
    lng: -3.7038,
    city: "Madrid",
  },
  createdAt: new Date("2024-01-15"),
}

export const mockUsers: User[] = [
  currentUser,
  {
    id: "user-2",
    name: "María López",
    username: "marialop",
    email: "maria@email.com",
    avatar: "/young-spanish-woman-smiling.jpg",
    description: "Fotógrafa aficionada y amante de los viajes",
    interests: ["Fotografía", "Viajes", "Arte"],
    location: { lat: 40.42, lng: -3.71, city: "Madrid" },
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "user-3",
    name: "Pablo Ruiz",
    username: "pabloruiz",
    email: "pablo@email.com",
    avatar: "/young-spanish-man-with-beard.jpg",
    description: "Deportista y cocinero en mis ratos libres",
    interests: ["Deportes", "Cocina", "Gaming"],
    location: { lat: 40.41, lng: -3.69, city: "Madrid" },
    createdAt: new Date("2024-03-05"),
  },
  {
    id: "user-4",
    name: "Laura Martín",
    username: "lauram",
    email: "laura@email.com",
    avatar: "/smiling-woman-glasses.png",
    description: "Exploradora urbana y cinéfila",
    interests: ["Cine", "Gastronomía", "Arte"],
    location: { lat: 40.43, lng: -3.7, city: "Madrid" },
    createdAt: new Date("2024-01-20"),
  },
]

export const mockPlans: Plan[] = [
  {
    id: "plan-1",
    title: "Partido de Pádel",
    description:
      "Buscamos dos jugadores más para completar un partido de pádel nivel intermedio. ¡Traed ganas de pasarlo bien!",
    image: "/padel-court-players.png",
    category: "Deportes",
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    time: "18:00",
    location: {
      name: "Club Pádel Madrid Centro",
      address: "Calle Gran Vía 45, Madrid",
      lat: 40.4203,
      lng: -3.7015,
      city: "Madrid",
    },
    maxParticipants: 4,
    currentParticipants: 2,
    pricePerPerson: 8,
    courtReservation: {
      courtName: "Pista 3",
      reservationTime: "18:00 - 19:30",
      price: 32,
    },
    creator: mockUsers[1],
    participants: [mockUsers[1], mockUsers[2]],
    createdAt: new Date(),
  },
  {
    id: "plan-2",
    title: "Ruta de Senderismo - Sierra de Guadarrama",
    description:
      "Ruta circular de dificultad media por la Sierra de Guadarrama. Aproximadamente 12km. Llevar agua y comida para el camino.",
    image: "/mountain-hiking-trail-spain.jpg",
    category: "Senderismo",
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    time: "09:00",
    location: {
      name: "Puerto de Navacerrada",
      address: "Puerto de Navacerrada, Madrid",
      lat: 40.7833,
      lng: -4.0167,
      city: "Navacerrada",
    },
    maxParticipants: 15,
    currentParticipants: 8,
    creator: mockUsers[2],
    participants: [mockUsers[2], mockUsers[0], mockUsers[3]],
    createdAt: new Date(),
  },
  {
    id: "plan-3",
    title: "Cena en nuevo restaurante japonés",
    description:
      "He descubierto un restaurante japonés nuevo que tiene muy buenas reseñas. ¿Alguien se apunta a probarlo?",
    image: "/japanese-restaurant-interior-modern.jpg",
    category: "Gastronomía",
    date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    time: "21:00",
    location: {
      name: "Osaka Izakaya",
      address: "Calle Fuencarral 78, Madrid",
      lat: 40.4256,
      lng: -3.7012,
      city: "Madrid",
    },
    maxParticipants: 8,
    currentParticipants: 4,
    pricePerPerson: 35,
    creator: mockUsers[3],
    participants: [mockUsers[3], mockUsers[1]],
    createdAt: new Date(),
  },
  {
    id: "plan-4",
    title: "Concierto indie en sala pequeña",
    description: "Concierto de una banda indie local que me han recomendado mucho. La entrada incluye consumición.",
    image: "/small-concert-venue-live-music.jpg",
    category: "Música",
    date: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
    time: "22:30",
    location: {
      name: "Sala El Sol",
      address: "Calle Jardines 3, Madrid",
      lat: 40.4198,
      lng: -3.7022,
      city: "Madrid",
    },
    maxParticipants: 10,
    currentParticipants: 6,
    pricePerPerson: 15,
    creator: mockUsers[1],
    participants: [mockUsers[1], mockUsers[0], mockUsers[2]],
    createdAt: new Date(),
  },
  {
    id: "plan-5",
    title: "Torneo de FIFA",
    description: "Organizamos un torneo de FIFA en mi casa. Habrá premios para los 3 primeros. Traed vuestros mandos!",
    image: "/gaming-setup-playstation-fifa.jpg",
    category: "Gaming",
    date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    time: "17:00",
    location: {
      name: "Casa de Pablo",
      address: "Calle Alcalá 120, Madrid",
      lat: 40.4234,
      lng: -3.6789,
      city: "Madrid",
    },
    maxParticipants: 16,
    currentParticipants: 10,
    creator: mockUsers[2],
    participants: [mockUsers[2], mockUsers[0]],
    createdAt: new Date(),
  },
  {
    id: "plan-6",
    title: "Clase de yoga al aire libre",
    description: "Clase de yoga para todos los niveles en el Retiro. Traed esterilla y ropa cómoda.",
    image: "/outdoor-yoga-class-park.jpg",
    category: "Bienestar",
    date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    time: "10:00",
    location: {
      name: "Parque del Retiro",
      address: "Paseo del Prado, Madrid",
      lat: 40.4153,
      lng: -3.6845,
      city: "Madrid",
    },
    maxParticipants: 20,
    currentParticipants: 12,
    creator: mockUsers[3],
    participants: [mockUsers[3], mockUsers[1]],
    createdAt: new Date(),
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    type: "new_plan",
    title: "Nuevo plan en tu zona",
    message: "María ha creado un plan de pádel cerca de ti",
    planId: "plan-1",
    read: false,
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
  },
  {
    id: "notif-2",
    type: "upcoming",
    title: "Plan mañana",
    message: "Recuerda: Clase de yoga en el Retiro mañana a las 10:00",
    planId: "plan-6",
    read: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: "notif-3",
    type: "plan_change",
    title: "Cambio en un plan",
    message: "El concierto indie ha cambiado de hora: ahora es a las 22:30",
    planId: "plan-4",
    read: true,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
  {
    id: "notif-4",
    type: "message",
    title: "Nuevo mensaje",
    message: "Pablo en 'Ruta de Senderismo': ¿Quedamos en el parking a las 8:30?",
    planId: "plan-2",
    read: true,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
  },
]

export const categories = [
  { id: "all", name: "Todos", icon: "Grid3X3" },
  { id: "deportes", name: "Deportes", icon: "Dumbbell" },
  { id: "senderismo", name: "Senderismo", icon: "Mountain" },
  { id: "gastronomia", name: "Gastronomía", icon: "UtensilsCrossed" },
  { id: "musica", name: "Música", icon: "Music" },
  { id: "gaming", name: "Gaming", icon: "Gamepad2" },
  { id: "bienestar", name: "Bienestar", icon: "Heart" },
  { id: "arte", name: "Arte", icon: "Palette" },
  { id: "viajes", name: "Viajes", icon: "Plane" },
]
